BackItems = {
    ['markedbills'] = { -- Item Name
        model = 'prop_money_bag_01', -- Model you want to display
        back_bone = 24818, -- PED bone the entity is attached to.
        -- Location of the model on the players back. Note this is and offset relative to the players bone coords.
        x = -0.4,
        y = -0.17,
        z = -0.12,
        -- Rotaion of the object.
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
    ['meth'] = {
        model = 'hei_prop_pill_bag_01',
        back_bone = 24818,
        x = -0.1,
        y = -0.17,
        z = 0.12,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
    ['weapon_smg'] = {
        model = 'w_sb_smg',
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ['weapon_assaultrifle'] = {
        model = 'w_ar_assaultrifle',
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.05,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ['weapon_carbinerifle_mk2'] = {
        model = 'w_ar_carbineriflemk2',
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ['weapon_carbinerifle'] = {
        model = 'w_ar_carbinerifle',
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ['weapon_pumpshotgun'] = {
        model = 'w_sg_pumpshotgun',
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 180.0,
        z_rotation = 180.0,
    },
    ['weapon_advancedrifle'] = {
        model = 'w_ar_advancedrifle',
        back_bone = 24818,
        x = 0.2,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 180.0,
        z_rotation = 180.0,
    },
    ['weapon_specialcarbine'] = {
        model = 'w_ar_specialcarbine',
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 180.0,
        z_rotation = 180.0,
    },
    ['weapon_bullpuprifle'] = {
        model = 'w_ar_bullpuprifle',
        back_bone = 24818,
        x = 0.1,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 180.0,
        z_rotation = 180.0,
    },
    ['weapon_microsmg'] = {
        model = 'w_sb_microsmg',
        back_bone = 24818,
        x = 0.1,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 180.0,
        z_rotation = 180.0,
    },
    ['weapon_smg_mk2'] = {
        model = 'w_sb_microsmg',
        back_bone = 24818,
        x = 0.1,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 180.0,
        z_rotation = 180.0,
    },
    ['weapon_assaultsmg'] = {
        model = 'w_sb_assaultsmg',
        back_bone = 24818,
        x = 0.1,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 180.0,
        z_rotation = 180.0,
    },
    ['weapon_combatpdw'] = {
        model = 'w_mg_combatmg',
        back_bone = 24818,
        x = 0.1,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 180.0,
        z_rotation = 180.0,
    },
    ['weapon_minismg'] = {
        model = 'w_sb_microsmg',
        back_bone = 24818,
        x = 0.1,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 180.0,
        z_rotation = 180.0,
    },
    ['weapon_bat'] = {
        model = 'w_me_bat',
        back_bone = 24818,
        x = -0.2,
        y = -0.17,
        z = 0.1,
        x_rotation = 90.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
    ['weapon_knife'] = {
        model = 'prop_cs_bowie_knife',
        back_bone = 24818,
        x = -0.3,
        y = -0.17,
        z = 0.1,
        x_rotation = 0.0,
        y_rotation = 180.0,
        z_rotation = 180.0,
    },
    ['cokebaggy'] = {
        model = 'bkr_prop_coke_cutblock_01',
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 90.0,
    },
    ['coke_brick'] = {
        model = 'bkr_prop_coke_cutblock_01',
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 90.0,
    },
    ['cannabis'] = {
        model = 'bkr_prop_weed_drying_01a',
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
    ['weapon_hammer'] = {
        model = 'w_me_hammer',
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
    ['drill'] = {
        model = 'prop_tool_drill',
        back_bone = 24818,
        x = -0.30,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 190.0,
        z_rotation = 0.0,
    },
}
